// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhOAT7qgNxdZ0FGTn2xIjNB3QiqKDVjKw',
    appId: '1:373430683771:web:7913ef330594ae82dc7ade',
    messagingSenderId: '373430683771',
    projectId: 'shopping-list-a80da',
    authDomain: 'shopping-list-a80da.firebaseapp.com',
    storageBucket: 'shopping-list-a80da.appspot.com',
    measurementId: 'G-Z1GLY3LL4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAo8Wzy4XtxIreLBPIPejmyVzAyUxXv_o',
    appId: '1:373430683771:android:d6c67988e42df572dc7ade',
    messagingSenderId: '373430683771',
    projectId: 'shopping-list-a80da',
    storageBucket: 'shopping-list-a80da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Wqyc3q1fnBI7sBhJZYqFVCqfSRUU2d4',
    appId: '1:373430683771:ios:388cba9ba323f5ccdc7ade',
    messagingSenderId: '373430683771',
    projectId: 'shopping-list-a80da',
    storageBucket: 'shopping-list-a80da.appspot.com',
    iosClientId: '373430683771-115selepddkal35lfmppc9jjitrfsirh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Wqyc3q1fnBI7sBhJZYqFVCqfSRUU2d4',
    appId: '1:373430683771:ios:d42261e714c98966dc7ade',
    messagingSenderId: '373430683771',
    projectId: 'shopping-list-a80da',
    storageBucket: 'shopping-list-a80da.appspot.com',
    iosClientId: '373430683771-6to51vtutn79aon9vko59soe2493o6je.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingList.RunnerTests',
  );
}
